# Welcome to Jekyll!
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nuri Tas Blog # Or your desired site title
email: nuri.tas@uzh.ch
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning Research
baseurl: "" # for user/organization pages (e.g., username.github.io), this is usually empty.
            # For project pages (e.g., username.github.io/project-name), set to "/project-name".
url: "https://nuritas.github.io" 

# Social Media (common in themes, check your theme's documentation for exact variable names)
linkedin_username: nuri-taş-744536234/ 

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown, good for code blocks
  syntax_highlighter: rouge
highlighter: rouge # For syntax highlighting in code blocks

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed    # For generating an Atom feed for your posts
- jekyll-seo-tag # For automatically adding SEO meta tags
- jekyll-sitemap # For generating a sitemap.xml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically
# added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.md
  # - any_other_files_or_folders_to_exclude.txt

# Default front matter for all posts and pages
# You can override these on a per-post or per-page basis
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post" # Assumes your theme has a 'post' layout
      # author: "Your Name" # If you want a default author for posts
      # categories: blog # Default category
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # Assumes your theme has a 'page' layout
      # title: "Page Title" # Often set in the page's front matter itself



# modernist_theme_options: # (Example - this key likely doesn't exist)
#   show_excerpts: true
#   footer_text: "© 2024 Your Name"
#   navigation: # Example navigation structure
#     - title: Home
#       url: /
#     - title: About
#       url: /about/
#     - title: Blog
#       url: /blog/
#     - title: Projects
#       url: /projects/
#   accent_color: "#3498db"

# --- END OF CONFIGURATION ---